sudo: required
dist: xenial
addons:
  chrome: stable

language: node_js
node_js:
  - "8"
 
services:
  - xvfb

branches:
  only:
    - master

cache:
  directories:
    - node_modules
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test
  - ng e2e
