sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - "8"

branches:
  only:
    - master

cache:
  directories:
    - node_modules
before_script:
  - npm install -g @angular/cli

script:
  - ng build --prod --aot
  - ng test
